server:
  port: 8888

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/ExampleDriven/spring-cloud-config-example
#          # The git repo will be cloned to this directory
#          basedir: target/config
#          # within the cloned git repo search for properties in this directory
#          searchPaths: properties-git
        native:
          searchLocations: /Users/pheerathach/Projects/grader/service-config-repo